-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.cities
(
    city_id integer NOT NULL,
    city_name character varying(20) NOT NULL,
    PRIMARY KEY (city_id)
);

CREATE TABLE public.employer_confirmation_by_employees
(
    confirm_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_confirmed boolean NOT NULL,
    approval_date time without time zone NOT NULL,
    employee_id integer NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (confirm_id)
);

CREATE TABLE public.cover_letters
(
    letter_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    letter_content character varying(400) NOT NULL,
    PRIMARY KEY (letter_id)
);

CREATE TABLE public.educations
(
    education_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    school_name character varying(255) NOT NULL,
    department character varying(255) NOT NULL,
    start_date date NOT NULL,
    graduated_date date,
    PRIMARY KEY (education_id)
);

CREATE TABLE public.employees
(
    user_id integer NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(150) NOT NULL,
    web_address character varying(50) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_advertisements
(
    advert_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employer_id integer NOT NULL,
    min_salary integer NOT NULL,
    max_salary integer NOT NULL,
    quota integer NOT NULL,
    last_application character varying(20) NOT NULL,
    created_date date NOT NULL,
    is_active boolean NOT NULL,
    position_id integer NOT NULL,
    job_description character varying(500) NOT NULL,
    city_id integer NOT NULL,
    job_advertisement_name character varying(200) NOT NULL,
    PRIMARY KEY (advert_id)
);

CREATE TABLE public.job_experiences
(
    experience_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    workplace_name character varying(255) NOT NULL,
    position_name character varying(255) NOT NULL,
    start_date date NOT NULL,
    leave_date date,
    PRIMARY KEY (experience_id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    identity_number character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.languages
(
    language_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    language_name character varying(255) NOT NULL,
    language_level integer NOT NULL,
    PRIMARY KEY (language_id)
);

CREATE TABLE public.links
(
    link_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    github_link character varying(300) NOT NULL,
    linkedin_link character varying(300) NOT NULL,
    PRIMARY KEY (link_id)
);

CREATE TABLE public.photos
(
    photo_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    photo_url character varying(255) NOT NULL,
    upload_date date NOT NULL,
    PRIMARY KEY (photo_id)
);

CREATE TABLE public.job_positions
(
    position_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying(30) NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public.technologies
(
    technology_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    job_seeker_id integer NOT NULL,
    technology_name character varying(255) NOT NULL,
    technology_level integer NOT NULL,
    PRIMARY KEY (technology_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    password_repeat character varying(50) NOT NULL,
    phone_number character(10) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.verifications
(
    verification_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    is_verified boolean NOT NULL,
    verification_code character varying(255) NOT NULL,
    user_id integer NOT NULL,
    verified_date date NOT NULL,
    PRIMARY KEY (verification_id)
);

ALTER TABLE public.employer_confirmation_by_employees
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employees (user_id)
    NOT VALID;


ALTER TABLE public.cover_letters
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.educations
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (position_id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (position_id)
    NOT VALID;


ALTER TABLE public.job_experiences
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.languages
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.links
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.photos
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.technologies
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.verifications
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employer_confirmation_by_employees
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (user_id)
    NOT VALID;

END;